const donorsData = [
  {
    "id": 125,
    "name": "Sangeetha Unni",
    "email": "sangeethaunni5875@yahoo.com",
    "contact": "9558835930",
    "place_of_residence": "Kaloor",
    "current_locality": "Palakkad",
    "age": 51,
    "weight": 63.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 6,
    "ml_score": 1.0
  },
  {
    "id": 134,
    "name": "Lekha Nair",
    "email": "lekhanair5560@hotmail.com",
    "contact": "8698128009",
    "place_of_residence": "Kottayam",
    "current_locality": "Kollam",
    "age": 48,
    "weight": 70.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 10,
    "ml_score": 1.0
  },
  {
    "id": 142,
    "name": "Nithin Khan",
    "email": "nithinkhan6573@gmail.com",
    "contact": "9047358091",
    "place_of_residence": "Kalamassery",
    "current_locality": "Kozhikode",
    "age": 21,
    "weight": 74.0,
    "blood_group": "B-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 9,
    "ml_score": 1.0
  },
  {
    "id": 147,
    "name": "Gautham Rajan",
    "email": "gauthamrajan5896@hotmail.com",
    "contact": "9836976310",
    "place_of_residence": "Kannur",
    "current_locality": "Angamaly",
    "age": 29,
    "weight": 73.0,
    "blood_group": "B-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 7,
    "ml_score": 1.0
  },
  {
    "id": 161,
    "name": "Riya Unni",
    "email": "riyaunni9654@gmail.com",
    "contact": "9465511542",
    "place_of_residence": "Pothanicad",
    "current_locality": "Kalampoor",
    "age": 34,
    "weight": 76.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 7,
    "ml_score": 1.0
  },
  {
    "id": 167,
    "name": "Dileep Lal",
    "email": "dileeplal4429@gmail.com",
    "contact": "9588079437",
    "place_of_residence": "Kalampoor",
    "current_locality": "Kakkanad",
    "age": 54,
    "weight": 59.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 10,
    "ml_score": 1.0
  },
  {
    "id": 50,
    "name": "Abdul Majeed",
    "email": "abdulmajeedppma@gmail.com",
    "contact": "9747082875",
    "place_of_residence": "Malappuram",
    "current_locality": "Manjeri",
    "age": 53,
    "weight": 70.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 1,
    "total_donations": 12,
    "ml_score": 0.99
  },
  {
    "id": 106,
    "name": "Arjun Biju",
    "email": "arjunbiju318@outlook.com",
    "contact": "9613685734",
    "place_of_residence": "Kothamangalam",
    "current_locality": "Moovattupuzha",
    "age": 36,
    "weight": 66.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 1,
    "total_donations": 8,
    "ml_score": 0.99
  },
  {
    "id": 117,
    "name": "Geethu Nampoothiri",
    "email": "geethunampoothiri6440@yahoo.com",
    "contact": "8601094760",
    "place_of_residence": "Kasaragod",
    "current_locality": "Kottayam",
    "age": 32,
    "weight": 57.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 1,
    "total_donations": 7,
    "ml_score": 0.99
  },
  {
    "id": 133,
    "name": "Akshay Lal",
    "email": "akshaylal8698@outlook.com",
    "contact": "9815430381",
    "place_of_residence": "Idukki",
    "current_locality": "Idukki",
    "age": 33,
    "weight": 71.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 2,
    "total_donations": 10,
    "ml_score": 0.99
  },
  {
    "id": 182,
    "name": "Meera Dev",
    "email": "meeradev7839@hotmail.com",
    "contact": "8272699184",
    "place_of_residence": "Kannur",
    "current_locality": "Kollam",
    "age": 32,
    "weight": 67.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 1,
    "total_donations": 8,
    "ml_score": 0.99
  },
  {
    "id": 185,
    "name": "Nithin Ali",
    "email": "nithinali6175@gmail.com",
    "contact": "8897018209",
    "place_of_residence": "Thripunithura",
    "current_locality": "Moovattupuzha",
    "age": 25,
    "weight": 58.0,
    "blood_group": "A-",
    "availability": false,
    "months_since_last_donation": 2,
    "total_donations": 8,
    "ml_score": 0.99
  },
  {
    "id": 81,
    "name": "Pradeep Varma",
    "email": "pradeepvarma4940@gmail.com",
    "contact": "8937384010",
    "place_of_residence": "Palakkad",
    "current_locality": "Kozhikode",
    "age": 52,
    "weight": 56.0,
    "blood_group": "B-",
    "availability": false,
    "months_since_last_donation": 4,
    "total_donations": 8,
    "ml_score": 0.98
  },
  {
    "id": 120,
    "name": "Jomon Mathew",
    "email": "jomonmathew7869@outlook.com",
    "contact": "8534793463",
    "place_of_residence": "Nellikuzhi",
    "current_locality": "Kozhikode",
    "age": 44,
    "weight": 73.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 4,
    "total_donations": 8,
    "ml_score": 0.98
  },
  {
    "id": 162,
    "name": "Vidya Nampoothiri",
    "email": "vidyanampoothiri1331@hotmail.com",
    "contact": "9416681904",
    "place_of_residence": "Kottayam",
    "current_locality": "Malappuram",
    "age": 30,
    "weight": 77.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 4,
    "total_donations": 9,
    "ml_score": 0.98
  },
  {
    "id": 104,
    "name": "Geethu Sivan",
    "email": "geethusivan2665@yahoo.com",
    "contact": "9406981822",
    "place_of_residence": "Palakkad",
    "current_locality": "Pathanamthitta",
    "age": 24,
    "weight": 78.0,
    "blood_group": "B-",
    "availability": false,
    "months_since_last_donation": 5,
    "total_donations": 10,
    "ml_score": 0.97
  },
  {
    "id": 168,
    "name": "Thomas John",
    "email": "thomasjohn3508@gmail.com",
    "contact": "8695621537",
    "place_of_residence": "Irinjalakuda",
    "current_locality": "Irinjalakuda",
    "age": 41,
    "weight": 77.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 5,
    "total_donations": 9,
    "ml_score": 0.97
  },
  {
    "id": 74,
    "name": "Manoj Paul",
    "email": "manojpaul739@outlook.com",
    "contact": "8200221097",
    "place_of_residence": "Guruvayur",
    "current_locality": "Guruvayur",
    "age": 24,
    "weight": 77.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 7,
    "total_donations": 5,
    "ml_score": 0.96
  },
  {
    "id": 153,
    "name": "Reshma Varma",
    "email": "reshmavarma6533@yahoo.com",
    "contact": "8917222344",
    "place_of_residence": "Kakkanad",
    "current_locality": "Perumbavoor",
    "age": 23,
    "weight": 79.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 4,
    "ml_score": 0.96
  },
  {
    "id": 165,
    "name": "Jithin Pillai",
    "email": "jithinpillai1328@yahoo.com",
    "contact": "8784785323",
    "place_of_residence": "Kolenchery",
    "current_locality": "Pathanamthitta",
    "age": 42,
    "weight": 63.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 4,
    "ml_score": 0.96
  },
  {
    "id": 51,
    "name": "Mansoor Ali T",
    "email": "mansoorali9895@gmail.com",
    "contact": "9895676860",
    "place_of_residence": "Malappuram",
    "current_locality": "Devathiyal",
    "age": 46,
    "weight": 69.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 1,
    "total_donations": 4,
    "ml_score": 0.95
  },
  {
    "id": 73,
    "name": "Sibin Das",
    "email": "sibindas3612@gmail.com",
    "contact": "7566349569",
    "place_of_residence": "Malappuram",
    "current_locality": "Pathanamthitta",
    "age": 40,
    "weight": 61.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 8,
    "total_donations": 8,
    "ml_score": 0.95
  },
  {
    "id": 128,
    "name": "Ribin Biju",
    "email": "ribinbiju1878@gmail.com",
    "contact": "8800758553",
    "place_of_residence": "Palakkad",
    "current_locality": "Aluva",
    "age": 37,
    "weight": 55.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 8,
    "total_donations": 8,
    "ml_score": 0.95
  },
  {
    "id": 156,
    "name": "Ramesh Raj",
    "email": "rameshraj9648@outlook.com",
    "contact": "7089025175",
    "place_of_residence": "Thrissur",
    "current_locality": "Palakkad",
    "age": 35,
    "weight": 76.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 9,
    "total_donations": 5,
    "ml_score": 0.95
  },
  {
    "id": 85,
    "name": "Krishnan George",
    "email": "krishnangeorge3611@hotmail.com",
    "contact": "8928818331",
    "place_of_residence": "Idukki",
    "current_locality": "Kozhikode",
    "age": 41,
    "weight": 71.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 10,
    "total_donations": 9,
    "ml_score": 0.94
  },
  {
    "id": 75,
    "name": "Gokul Raj",
    "email": "gokulraj112@yahoo.com",
    "contact": "8881286354",
    "place_of_residence": "Kollam",
    "current_locality": "Perumbavoor",
    "age": 48,
    "weight": 56.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 11,
    "total_donations": 9,
    "ml_score": 0.93
  },
  {
    "id": 89,
    "name": "Suresh Pillai",
    "email": "sureshpillai5116@gmail.com",
    "contact": "9760664653",
    "place_of_residence": "Kalampoor",
    "current_locality": "Kollam",
    "age": 25,
    "weight": 67.0,
    "blood_group": "B-",
    "availability": true,
    "months_since_last_donation": 12,
    "total_donations": 5,
    "ml_score": 0.93
  },
  {
    "id": 155,
    "name": "Noufal Sivan",
    "email": "noufalsivan5779@hotmail.com",
    "contact": "8284732408",
    "place_of_residence": "Nellikuzhi",
    "current_locality": "Kalampoor",
    "age": 49,
    "weight": 70.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 12,
    "total_donations": 8,
    "ml_score": 0.93
  },
  {
    "id": 183,
    "name": "Sandhya Sivan",
    "email": "sandhyasivan8374@hotmail.com",
    "contact": "8708431854",
    "place_of_residence": "Kalamassery",
    "current_locality": "Piravom",
    "age": 55,
    "weight": 64.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 12,
    "total_donations": 9,
    "ml_score": 0.93
  },
  {
    "id": 190,
    "name": "Akshay Unni",
    "email": "akshayunni6382@outlook.com",
    "contact": "8875349330",
    "place_of_residence": "Kottayam",
    "current_locality": "Muvattupuzha",
    "age": 31,
    "weight": 69.0,
    "blood_group": "B-",
    "availability": false,
    "months_since_last_donation": 12,
    "total_donations": 5,
    "ml_score": 0.93
  },
  {
    "id": 126,
    "name": "Lijo Menon",
    "email": "lijomenon6063@hotmail.com",
    "contact": "7576739133",
    "place_of_residence": "Irinjalakuda",
    "current_locality": "Nellikuzhi",
    "age": 19,
    "weight": 63.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 3,
    "ml_score": 0.92
  },
  {
    "id": 166,
    "name": "Muhammed Khan",
    "email": "muhammedkhan8575@gmail.com",
    "contact": "7529280444",
    "place_of_residence": "Pothanicad",
    "current_locality": "Palakkad",
    "age": 25,
    "weight": 73.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 3,
    "ml_score": 0.92
  },
  {
    "id": 79,
    "name": "Salu Jacob",
    "email": "salujacob8582@hotmail.com",
    "contact": "9439992343",
    "place_of_residence": "Kalampoor",
    "current_locality": "Guruvayur",
    "age": 52,
    "weight": 93.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 7,
    "ml_score": 0.91
  },
  {
    "id": 102,
    "name": "Sheeba Ali",
    "email": "sheebaali6044@gmail.com",
    "contact": "7074893160",
    "place_of_residence": "Thripunithura",
    "current_locality": "Kakkanad",
    "age": 34,
    "weight": 67.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 1,
    "total_donations": 3,
    "ml_score": 0.91
  },
  {
    "id": 107,
    "name": "Amal Philip",
    "email": "amalphilip4765@gmail.com",
    "contact": "9077886408",
    "place_of_residence": "Kunnamkulam",
    "current_locality": "Angamaly",
    "age": 54,
    "weight": 72.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 8,
    "total_donations": 4,
    "ml_score": 0.91
  },
  {
    "id": 116,
    "name": "Rekha Panicker",
    "email": "rekhapanicker5040@gmail.com",
    "contact": "9080505707",
    "place_of_residence": "Ernakulam",
    "current_locality": "Kolenchery",
    "age": 37,
    "weight": 45.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 5,
    "ml_score": 0.91
  },
  {
    "id": 150,
    "name": "Keerthana Krishnan",
    "email": "keerthanakrishnan9846@gmail.com",
    "contact": "8833447491",
    "place_of_residence": "Idukki",
    "current_locality": "Moovattupuzha",
    "age": 32,
    "weight": 97.0,
    "blood_group": "A-",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 5,
    "ml_score": 0.91
  },
  {
    "id": 169,
    "name": "Lijesh Nair",
    "email": "lijeshnair7141@outlook.com",
    "contact": "9157342069",
    "place_of_residence": "Pothanicad",
    "current_locality": "Kakkanad",
    "age": 21,
    "weight": 53.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 5,
    "ml_score": 0.91
  },
  {
    "id": 171,
    "name": "Manju Mathew",
    "email": "manjumathew5490@outlook.com",
    "contact": "8970575999",
    "place_of_residence": "Thrippunithura",
    "current_locality": "Thrissur",
    "age": 49,
    "weight": 91.0,
    "blood_group": "B-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 5,
    "ml_score": 0.91
  },
  {
    "id": 76,
    "name": "Kavitha Suresh",
    "email": "kavithasuresh6564@hotmail.com",
    "contact": "8128317470",
    "place_of_residence": "Kozhikode",
    "current_locality": "Kottayam",
    "age": 41,
    "weight": 45.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 1,
    "total_donations": 10,
    "ml_score": 0.9
  },
  {
    "id": 177,
    "name": "Subin Babu",
    "email": "subinbabu5794@hotmail.com",
    "contact": "8832348192",
    "place_of_residence": "Piravom",
    "current_locality": "Nellikuzhi",
    "age": 39,
    "weight": 96.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 2,
    "total_donations": 5,
    "ml_score": 0.9
  },
  {
    "id": 180,
    "name": "Minu Nair",
    "email": "minunair5181@yahoo.com",
    "contact": "8868914459",
    "place_of_residence": "Malappuram",
    "current_locality": "Kaloor",
    "age": 18,
    "weight": 74.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 3,
    "total_donations": 3,
    "ml_score": 0.9
  },
  {
    "id": 188,
    "name": "Rohith Lal",
    "email": "rohithlal8801@outlook.com",
    "contact": "9687611158",
    "place_of_residence": "Irinjalakuda",
    "current_locality": "Pathanamthitta",
    "age": 47,
    "weight": 49.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 2,
    "total_donations": 6,
    "ml_score": 0.9
  },
  {
    "id": 121,
    "name": "Dinesh Ali",
    "email": "dineshali1907@gmail.com",
    "contact": "9855579392",
    "place_of_residence": "Kaloor",
    "current_locality": "Idukki",
    "age": 19,
    "weight": 47.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 4,
    "total_donations": 10,
    "ml_score": 0.89
  },
  {
    "id": 130,
    "name": "Manoj Hussain",
    "email": "manojhussain1297@gmail.com",
    "contact": "8215288651",
    "place_of_residence": "Kakkanad",
    "current_locality": "Kochi",
    "age": 34,
    "weight": 95.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 4,
    "total_donations": 6,
    "ml_score": 0.89
  },
  {
    "id": 181,
    "name": "Arun Lal",
    "email": "arunlal4359@yahoo.com",
    "contact": "7539672501",
    "place_of_residence": "Edapally",
    "current_locality": "Kottayam",
    "age": 23,
    "weight": 86.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 4,
    "total_donations": 7,
    "ml_score": 0.89
  },
  {
    "id": 77,
    "name": "Diljith Nampoothiri",
    "email": "diljithnampoothiri486@outlook.com",
    "contact": "8861393977",
    "place_of_residence": "Kakkanad",
    "current_locality": "Idukki",
    "age": 21,
    "weight": 65.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 2,
    "ml_score": 0.88
  },
  {
    "id": 84,
    "name": "Prince Kurup",
    "email": "princekurup2772@hotmail.com",
    "contact": "8852289974",
    "place_of_residence": "Muvattupuzha",
    "current_locality": "Kannur",
    "age": 41,
    "weight": 54.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 5,
    "total_donations": 10,
    "ml_score": 0.88
  },
  {
    "id": 173,
    "name": "Neethu Suresh",
    "email": "neethusuresh2882@hotmail.com",
    "contact": "8096210624",
    "place_of_residence": "Kodungallur",
    "current_locality": "Nellikuzhi",
    "age": 54,
    "weight": 67.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 2,
    "ml_score": 0.88
  },
  {
    "id": 78,
    "name": "Parvathi Panicker",
    "email": "parvathipanicker4867@outlook.com",
    "contact": "8799066279",
    "place_of_residence": "Kannur",
    "current_locality": "Kaloor",
    "age": 26,
    "weight": 87.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 4,
    "ml_score": 0.87
  },
  {
    "id": 88,
    "name": "Harikrishna George",
    "email": "harikrishnageorge6966@hotmail.com",
    "contact": "9860971427",
    "place_of_residence": "Guruvayur",
    "current_locality": "Alappuzha",
    "age": 18,
    "weight": 83.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 7,
    "total_donations": 7,
    "ml_score": 0.87
  },
  {
    "id": 98,
    "name": "Deepak Thomas",
    "email": "deepakthomas6557@gmail.com",
    "contact": "8555660617",
    "place_of_residence": "Angamaly",
    "current_locality": "Kochi",
    "age": 55,
    "weight": 54.0,
    "blood_group": "AB-",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 4,
    "ml_score": 0.87
  },
  {
    "id": 139,
    "name": "Manju Raj",
    "email": "manjuraj9035@yahoo.com",
    "contact": "8641175937",
    "place_of_residence": "Moovattupuzha",
    "current_locality": "Guruvayur",
    "age": 41,
    "weight": 100.0,
    "blood_group": "A+",
    "availability": false,
    "months_since_last_donation": 6,
    "total_donations": 9,
    "ml_score": 0.87
  },
  {
    "id": 68,
    "name": "Mohammed Saneen k",
    "email": "saneenmohd3@gmail.com",
    "contact": "8089528053",
    "place_of_residence": "Malappuram",
    "current_locality": "Muvattupuzha",
    "age": 22,
    "weight": 72.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 3,
    "total_donations": 2,
    "ml_score": 0.86
  },
  {
    "id": 71,
    "name": "Arun Unni",
    "email": "arununni8273@yahoo.com",
    "contact": "7575618883",
    "place_of_residence": "Kothamangalam",
    "current_locality": "Moovattupuzha",
    "age": 44,
    "weight": 47.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 8,
    "total_donations": 5,
    "ml_score": 0.86
  },
  {
    "id": 83,
    "name": "Pooja Nampoothiri",
    "email": "poojanampoothiri6153@gmail.com",
    "contact": "9043738952",
    "place_of_residence": "Kalamassery",
    "current_locality": "Moovattupuzha",
    "age": 21,
    "weight": 55.0,
    "blood_group": "A+",
    "availability": false,
    "months_since_last_donation": 3,
    "total_donations": 2,
    "ml_score": 0.86
  },
  {
    "id": 127,
    "name": "Jobin Kumar",
    "email": "jobinkumar3971@outlook.com",
    "contact": "8967660189",
    "place_of_residence": "Kalamassery",
    "current_locality": "Guruvayur",
    "age": 31,
    "weight": 96.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 8,
    "total_donations": 5,
    "ml_score": 0.86
  },
  {
    "id": 132,
    "name": "Bindhu Hussain",
    "email": "bindhuhussain5124@gmail.com",
    "contact": "8652151974",
    "place_of_residence": "Malappuram",
    "current_locality": "Malappuram",
    "age": 42,
    "weight": 89.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 9,
    "total_donations": 5,
    "ml_score": 0.86
  },
  {
    "id": 136,
    "name": "Haritha Babu",
    "email": "harithababu7313@hotmail.com",
    "contact": "7080474647",
    "place_of_residence": "Idukki",
    "current_locality": "Thiruvananthapuram",
    "age": 37,
    "weight": 46.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 8,
    "total_donations": 5,
    "ml_score": 0.86
  },
  {
    "id": 154,
    "name": "Sangeetha Dev",
    "email": "sangeethadev4637@hotmail.com",
    "contact": "8959457976",
    "place_of_residence": "Edapally",
    "current_locality": "Guruvayur",
    "age": 52,
    "weight": 94.0,
    "blood_group": "A-",
    "availability": false,
    "months_since_last_donation": 9,
    "total_donations": 5,
    "ml_score": 0.86
  },
  {
    "id": 157,
    "name": "Fahad Suresh",
    "email": "fahadsuresh9200@outlook.com",
    "contact": "9149377902",
    "place_of_residence": "Thrippunithura",
    "current_locality": "Thrissur",
    "age": 47,
    "weight": 88.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 2,
    "total_donations": 4,
    "ml_score": 0.86
  },
  {
    "id": 164,
    "name": "Rony Jacob",
    "email": "ronyjacob5122@outlook.com",
    "contact": "9544335700",
    "place_of_residence": "Muvattupuzha",
    "current_locality": "Kalamassery",
    "age": 44,
    "weight": 88.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 8,
    "total_donations": 10,
    "ml_score": 0.86
  },
  {
    "id": 109,
    "name": "Irfan Hussain",
    "email": "irfanhussain970@yahoo.com",
    "contact": "9087724291",
    "place_of_residence": "Pathanamthitta",
    "current_locality": "Kunnamkulam",
    "age": 30,
    "weight": 81.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 10,
    "total_donations": 8,
    "ml_score": 0.85
  },
  {
    "id": 122,
    "name": "Arun Paul",
    "email": "arunpaul4820@gmail.com",
    "contact": "8110725843",
    "place_of_residence": "Irinjalakuda",
    "current_locality": "Thripunithura",
    "age": 37,
    "weight": 91.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 3,
    "total_donations": 4,
    "ml_score": 0.85
  },
  {
    "id": 138,
    "name": "Unnikrishnan Hussain",
    "email": "unnikrishnanhussain4517@outlook.com",
    "contact": "9788078551",
    "place_of_residence": "Kalamassery",
    "current_locality": "Ernakulam",
    "age": 29,
    "weight": 85.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 10,
    "total_donations": 7,
    "ml_score": 0.85
  },
  {
    "id": 158,
    "name": "Riya Krishnan",
    "email": "riyakrishnan5809@outlook.com",
    "contact": "8844675299",
    "place_of_residence": "Kozhikode",
    "current_locality": "Thrissur",
    "age": 20,
    "weight": 95.0,
    "blood_group": "AB+",
    "availability": false,
    "months_since_last_donation": 10,
    "total_donations": 9,
    "ml_score": 0.85
  },
  {
    "id": 178,
    "name": "Bindhu Kumar",
    "email": "bindhukumar9663@yahoo.com",
    "contact": "9800923413",
    "place_of_residence": "Nellikuzhi",
    "current_locality": "Thrissur",
    "age": 50,
    "weight": 95.0,
    "blood_group": "B+",
    "availability": false,
    "months_since_last_donation": 10,
    "total_donations": 7,
    "ml_score": 0.85
  },
  {
    "id": 189,
    "name": "Remya Sivan",
    "email": "remyasivan6349@hotmail.com",
    "contact": "8187367933",
    "place_of_residence": "Palakkad",
    "current_locality": "Muvattupuzha",
    "age": 33,
    "weight": 92.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 4,
    "total_donations": 4,
    "ml_score": 0.85
  },
  {
    "id": 100,
    "name": "Boban Unni",
    "email": "bobanunni1665@hotmail.com",
    "contact": "7063962235",
    "place_of_residence": "Ernakulam",
    "current_locality": "Pothanicad",
    "age": 45,
    "weight": 96.0,
    "blood_group": "AB+",
    "availability": false,
    "months_since_last_donation": 11,
    "total_donations": 6,
    "ml_score": 0.84
  },
  {
    "id": 123,
    "name": "Hisham Krishnan",
    "email": "hishamkrishnan1485@gmail.com",
    "contact": "8621173088",
    "place_of_residence": "Angamaly",
    "current_locality": "Kottayam",
    "age": 49,
    "weight": 98.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 11,
    "total_donations": 9,
    "ml_score": 0.84
  },
  {
    "id": 143,
    "name": "Neethu Nambiar",
    "email": "neethunambiar810@outlook.com",
    "contact": "8556887458",
    "place_of_residence": "Thrissur",
    "current_locality": "Palakkad",
    "age": 50,
    "weight": 100.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 12,
    "total_donations": 5,
    "ml_score": 0.84
  },
  {
    "id": 144,
    "name": "Ebin Khan",
    "email": "ebinkhan9231@yahoo.com",
    "contact": "8905707813",
    "place_of_residence": "Thiruvananthapuram",
    "current_locality": "Perumbavoor",
    "age": 29,
    "weight": 99.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 12,
    "total_donations": 5,
    "ml_score": 0.84
  },
  {
    "id": 152,
    "name": "Libin Philip",
    "email": "libinphilip5672@hotmail.com",
    "contact": "8791062752",
    "place_of_residence": "Guruvayur",
    "current_locality": "Guruvayur",
    "age": 43,
    "weight": 67.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 1,
    "ml_score": 0.84
  },
  {
    "id": 159,
    "name": "Dinesh Philip",
    "email": "dineshphilip5494@gmail.com",
    "contact": "8815556140",
    "place_of_residence": "Piravom",
    "current_locality": "Nellikuzhi",
    "age": 39,
    "weight": 94.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 11,
    "total_donations": 7,
    "ml_score": 0.84
  },
  {
    "id": 163,
    "name": "Serena Khan",
    "email": "serenakhan5266@outlook.com",
    "contact": "9667451502",
    "place_of_residence": "Thrippunithura",
    "current_locality": "Aluva",
    "age": 45,
    "weight": 83.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 12,
    "total_donations": 10,
    "ml_score": 0.84
  },
  {
    "id": 170,
    "name": "Biju Suresh",
    "email": "bijusuresh467@yahoo.com",
    "contact": "7054690315",
    "place_of_residence": "Nellikuzhi",
    "current_locality": "Alappuzha",
    "age": 40,
    "weight": 84.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 11,
    "total_donations": 9,
    "ml_score": 0.84
  },
  {
    "id": 172,
    "name": "Jithin Nambiar",
    "email": "jithinnambiar7350@yahoo.com",
    "contact": "8001024588",
    "place_of_residence": "Guruvayur",
    "current_locality": "Angamaly",
    "age": 53,
    "weight": 59.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 1,
    "ml_score": 0.84
  },
  {
    "id": 179,
    "name": "Athira Unni",
    "email": "athiraunni9030@gmail.com",
    "contact": "8553814079",
    "place_of_residence": "Kollam",
    "current_locality": "Ernakulam",
    "age": 51,
    "weight": 88.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 11,
    "total_donations": 6,
    "ml_score": 0.84
  },
  {
    "id": 10,
    "name": "Eldhose Reji",
    "email": "eldhosereji@gmail.com",
    "contact": "8075750058",
    "place_of_residence": "Ernakulam",
    "current_locality": "Mathirapilli",
    "age": 21,
    "weight": 69.0,
    "blood_group": "A+",
    "availability": false,
    "months_since_last_donation": 1,
    "total_donations": 1,
    "ml_score": 0.83
  },
  {
    "id": 72,
    "name": "Jomon Das",
    "email": "jomondas1553@hotmail.com",
    "contact": "7581266255",
    "place_of_residence": "Kozhikode",
    "current_locality": "Pothanicad",
    "age": 22,
    "weight": 86.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 3,
    "ml_score": 0.83
  },
  {
    "id": 99,
    "name": "Vishnu Menon",
    "email": "vishnumenon3237@hotmail.com",
    "contact": "8894508487",
    "place_of_residence": "Ernakulam",
    "current_locality": "Ernakulam",
    "age": 23,
    "weight": 46.0,
    "blood_group": "B-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 3,
    "ml_score": 0.83
  },
  {
    "id": 141,
    "name": "Salu Biju",
    "email": "salubiju1164@yahoo.com",
    "contact": "9475691988",
    "place_of_residence": "Kollam",
    "current_locality": "Kozhikode",
    "age": 23,
    "weight": 94.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 3,
    "ml_score": 0.83
  },
  {
    "id": 15,
    "name": "Kareem C A",
    "email": "kareemca2005@gmail.com",
    "contact": "8590234357",
    "place_of_residence": "Ernakulam",
    "current_locality": "Peezhakkapilly",
    "age": 21,
    "weight": 68.0,
    "blood_group": "AB+",
    "availability": false,
    "months_since_last_donation": 3,
    "total_donations": 1,
    "ml_score": 0.82
  },
  {
    "id": 93,
    "name": "Krishnan Das",
    "email": "krishnandas5323@hotmail.com",
    "contact": "8705820921",
    "place_of_residence": "Irinjalakuda",
    "current_locality": "Thripunithura",
    "age": 40,
    "weight": 55.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 4,
    "total_donations": 1,
    "ml_score": 0.82
  },
  {
    "id": 114,
    "name": "Reshma Jose",
    "email": "reshmajose6690@outlook.com",
    "contact": "9504425862",
    "place_of_residence": "Kozhikode",
    "current_locality": "Pathanamthitta",
    "age": 35,
    "weight": 83.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 2,
    "total_donations": 3,
    "ml_score": 0.82
  },
  {
    "id": 148,
    "name": "Muhammed Jacob",
    "email": "muhammedjacob1484@hotmail.com",
    "contact": "9126441796",
    "place_of_residence": "Kakkanad",
    "current_locality": "Thrissur",
    "age": 24,
    "weight": 72.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 10,
    "total_donations": 2,
    "ml_score": 0.82
  },
  {
    "id": 12,
    "name": "Mohammed Faiz",
    "email": "faiz150604@gmail.com",
    "contact": "7012772428",
    "place_of_residence": "Ernakulam",
    "current_locality": "Fort Kochi",
    "age": 21,
    "weight": 80.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 5,
    "total_donations": 1,
    "ml_score": 0.81
  },
  {
    "id": 135,
    "name": "Vidya Mohan",
    "email": "vidyamohan3578@yahoo.com",
    "contact": "9704896033",
    "place_of_residence": "Kothamangalam",
    "current_locality": "Alappuzha",
    "age": 42,
    "weight": 70.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 12,
    "total_donations": 2,
    "ml_score": 0.81
  },
  {
    "id": 4,
    "name": "Ansal C M",
    "email": "rasalansal@gmail.com",
    "contact": "8129966713",
    "place_of_residence": "Ernakulam",
    "current_locality": "Perumbavoor",
    "age": 20,
    "weight": 55.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 6,
    "name": "Deepak sanil",
    "email": "deepaksanil620@gmail.com",
    "contact": "9746736800",
    "place_of_residence": "Ernakulam",
    "current_locality": "Kothamangalam",
    "age": 20,
    "weight": 70.0,
    "blood_group": "B-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 7,
    "name": "Muhammed Sahal",
    "email": "muhammedsahal708@gmail.com",
    "contact": "9061094801",
    "place_of_residence": "Ernakulam",
    "current_locality": "Muvattupuzha",
    "age": 23,
    "weight": 78.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 8,
    "name": "Irfan Haris",
    "email": "irfan1234@gmail.com",
    "contact": "9847640538",
    "place_of_residence": "Alappuzha",
    "current_locality": "Mulavoor",
    "age": 21,
    "weight": 58.0,
    "blood_group": "O-",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 13,
    "name": "Eugin Shibu",
    "email": "euginshibu180@gmail.com",
    "contact": "7306121782",
    "place_of_residence": "Ernakulam",
    "current_locality": "Puduppady",
    "age": 21,
    "weight": 58.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 14,
    "name": "Ashiq Shaji",
    "email": "ashyqsha@gmail.com",
    "contact": "7025909708",
    "place_of_residence": "Idukki",
    "current_locality": "Muvattupuzha",
    "age": 23,
    "weight": 58.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 16,
    "name": "Muhammed Yazil Ajeeb",
    "email": "yazilajeeb386@gmail.com",
    "contact": "9633273181",
    "place_of_residence": "Kottayam",
    "current_locality": "Perumattam",
    "age": 25,
    "weight": 78.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 17,
    "name": "Eesa P Muhammadali",
    "email": "hiizzah46@gmail.com",
    "contact": "8137982547",
    "place_of_residence": "Ernakulam",
    "current_locality": "Kothamangalam",
    "age": 21,
    "weight": 55.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 18,
    "name": "Muhammed Irfan T A",
    "email": "muhmdirfanirfu068@gmail.com",
    "contact": "9778557081",
    "place_of_residence": "Ernakulam",
    "current_locality": "Aluva",
    "age": 21,
    "weight": 67.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 19,
    "name": "Ananda Krishnan A",
    "email": "anandakrishnana23ai@icet.in",
    "contact": "9656388045",
    "place_of_residence": "Idukki",
    "current_locality": "Thrissur",
    "age": 21,
    "weight": 59.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 20,
    "name": "Muhammed Rifah M K",
    "email": "muhammedrifah9090@gmail.com",
    "contact": "7902554417",
    "place_of_residence": "Kozhikode",
    "current_locality": "Kannur",
    "age": 21,
    "weight": 73.0,
    "blood_group": "B+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 21,
    "name": "Able Eldhose",
    "email": "ableeldhose11@gmail.com",
    "contact": "9207738584",
    "place_of_residence": "Ernakulam",
    "current_locality": "Muvattupuzha",
    "age": 21,
    "weight": 56.0,
    "blood_group": "B+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 23,
    "name": "Gouree Shankar",
    "email": "goureehari@gmail.com",
    "contact": "9961450841",
    "place_of_residence": "Ernakulam",
    "current_locality": "Muvattupuzha",
    "age": 21,
    "weight": 57.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 24,
    "name": "Moosa Sageer",
    "email": "moosasageer197@gmail.com",
    "contact": "8891437813",
    "place_of_residence": "Ernakulam",
    "current_locality": "Perumbavoor",
    "age": 21,
    "weight": 64.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 25,
    "name": "Mohammed Shahsad Sha",
    "email": "shasadsha@gmail.com",
    "contact": "9847549961",
    "place_of_residence": "Thrissur",
    "current_locality": "Palakkad",
    "age": 22,
    "weight": 65.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 27,
    "name": "Afna Kabeer",
    "email": "afnakabeer37@gmail.com",
    "contact": "7012137671",
    "place_of_residence": "Idukki",
    "current_locality": "Chalakudy",
    "age": 22,
    "weight": 56.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 31,
    "name": "Amalna Sherif",
    "email": "amalnasherif2@gmail.com",
    "contact": "7907419304",
    "place_of_residence": "Ernakulam",
    "current_locality": "Cheruvattoor",
    "age": 21,
    "weight": 55.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 32,
    "name": "Shifana E M",
    "email": "shifana567@gmail.com",
    "contact": "8075213014",
    "place_of_residence": "Ernakulam",
    "current_locality": "Aluva",
    "age": 20,
    "weight": 56.0,
    "blood_group": "B+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 34,
    "name": "Fariza Noushad",
    "email": "farizanoushad2004@gmail.com",
    "contact": "9446508915",
    "place_of_residence": "Ernakulam",
    "current_locality": "Muvattupuzha",
    "age": 21,
    "weight": 58.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 37,
    "name": "Farha C Ali",
    "email": "Farhacali@gmail.com",
    "contact": "9961872731",
    "place_of_residence": "Ernakulam",
    "current_locality": "Peezhakkapilly",
    "age": 21,
    "weight": 65.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 39,
    "name": "Lakshmi K U",
    "email": "lakshmiudhayan09@gmail.com",
    "contact": "6235778841",
    "place_of_residence": "Thirssur",
    "current_locality": "Trivandrum",
    "age": 20,
    "weight": 65.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 40,
    "name": "Ihsan Ahammed V N",
    "email": "ihsanahammedvn@gmail.com",
    "contact": "9446260603",
    "place_of_residence": "Idukki",
    "current_locality": "Vannapuram",
    "age": 19,
    "weight": 78.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 41,
    "name": "Alfiya K S",
    "email": "Aalfiyaks@gmail.com",
    "contact": "9188565593",
    "place_of_residence": "Ernakulam",
    "current_locality": "Muvattupuzha",
    "age": 21,
    "weight": 58.0,
    "blood_group": "B+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 46,
    "name": "Arya Mohan",
    "email": "aryamohan974@gmail.com",
    "contact": "9745435117",
    "place_of_residence": "Ernakulam",
    "current_locality": "Muvattupuzha",
    "age": 35,
    "weight": 59.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 47,
    "name": "Alvin Biju",
    "email": "alvinbiju04@gmail.com",
    "contact": "9747848675",
    "place_of_residence": "Ernakulam",
    "current_locality": "Kothamangalam",
    "age": 22,
    "weight": 65.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 48,
    "name": "Abhiram S",
    "email": "ars.abhiram@gmail.com",
    "contact": "7034718372",
    "place_of_residence": "Ernakulam",
    "current_locality": "Kothamangalam",
    "age": 22,
    "weight": 75.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 49,
    "name": "Mohmmed Yasin",
    "email": "Yasinpp98@gmail.com",
    "contact": "9544256295",
    "place_of_residence": "Malapuram",
    "current_locality": "Manjeri",
    "age": 26,
    "weight": 65.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 52,
    "name": "Ayishabi",
    "email": "ayishabip5256@gmail.com",
    "contact": "9745099520",
    "place_of_residence": "Malappuram",
    "current_locality": "Manjeri",
    "age": 50,
    "weight": 55.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 53,
    "name": "Febina Mol",
    "email": "Febinamolpp8582@gmail.com",
    "contact": "9633218582",
    "place_of_residence": "Malappuram",
    "current_locality": "Cherani",
    "age": 35,
    "weight": 60.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 54,
    "name": "Sabeer P K",
    "email": "Sabeerpk@gmail.com",
    "contact": "8111966690",
    "place_of_residence": "Malappuram",
    "current_locality": "Cherani",
    "age": 48,
    "weight": 67.0,
    "blood_group": "A+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 55,
    "name": "Jaseena K",
    "email": "jaseemansoor9995@gmail.com",
    "contact": "9747776451",
    "place_of_residence": "Malappuram",
    "current_locality": "Devathiyal",
    "age": 40,
    "weight": 67.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 57,
    "name": "Aman Zashil T",
    "email": "amanzash12@gmail.com",
    "contact": "9995378378",
    "place_of_residence": "Malappuram",
    "current_locality": "Devathiyal",
    "age": 19,
    "weight": 55.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 58,
    "name": "Devika sanik",
    "email": "devika22@gmail.com",
    "contact": "8085902025",
    "place_of_residence": "Ernakulam",
    "current_locality": "Muvattupuzha",
    "age": 22,
    "weight": 55.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 59,
    "name": "Ameer ali",
    "email": "ameer213@gmail.com",
    "contact": "9757211478",
    "place_of_residence": "Ernakulam",
    "current_locality": "Kothamangalam",
    "age": 26,
    "weight": 60.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 61,
    "name": "Adhil Ameen",
    "email": "adhilameen18@gmail.com",
    "contact": "7736544589",
    "place_of_residence": "Ernakulam",
    "current_locality": "Kothamangalam",
    "age": 24,
    "weight": 75.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 62,
    "name": "Deepak sanil",
    "email": "deepaksanil620@gmail.com",
    "contact": "9746736800",
    "place_of_residence": "Muvattupuzha",
    "current_locality": "Muvattupuzha",
    "age": 20,
    "weight": 70.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 65,
    "name": "Devanandh ",
    "email": "devanandhsreekumar2@gmail.com",
    "contact": "8590595112",
    "place_of_residence": "Muvattpuzhaa",
    "current_locality": "Kalampoor",
    "age": 19,
    "weight": 75.0,
    "blood_group": "B-",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 66,
    "name": "Minu Rees",
    "email": "minureesal7260@gmail.com",
    "contact": "7994157370",
    "place_of_residence": "Perumattom",
    "current_locality": "Perumattom",
    "age": 33,
    "weight": 63.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 86,
    "name": "Uma Ali",
    "email": "umaali6721@outlook.com",
    "contact": "9709300139",
    "place_of_residence": "Ernakulam",
    "current_locality": "Kasaragod",
    "age": 53,
    "weight": 69.0,
    "blood_group": "B-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 90,
    "name": "Mohammed Khan",
    "email": "mohammedkhan800@yahoo.com",
    "contact": "9814461600",
    "place_of_residence": "Kozhikode",
    "current_locality": "Ernakulam",
    "age": 37,
    "weight": 78.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 160,
    "name": "Sachin John",
    "email": "sachinjohn6867@outlook.com",
    "contact": "9648109991",
    "place_of_residence": "Kalamassery",
    "current_locality": "Kollam",
    "age": 27,
    "weight": 64.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.8
  },
  {
    "id": 131,
    "name": "Harikrishna Kumar",
    "email": "harikrishnakumar1372@yahoo.com",
    "contact": "9180337340",
    "place_of_residence": "Thrippunithura",
    "current_locality": "Thrippunithura",
    "age": 48,
    "weight": 57.0,
    "blood_group": "AB-",
    "availability": false,
    "months_since_last_donation": 2,
    "total_donations": 0,
    "ml_score": 0.79
  },
  {
    "id": 176,
    "name": "Riya Panicker",
    "email": "riyapanicker4023@yahoo.com",
    "contact": "9872449995",
    "place_of_residence": "Thripunithura",
    "current_locality": "Kakkanad",
    "age": 53,
    "weight": 80.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 1,
    "total_donations": 0,
    "ml_score": 0.79
  },
  {
    "id": 184,
    "name": "Haritha Rajan",
    "email": "haritharajan282@outlook.com",
    "contact": "9777993095",
    "place_of_residence": "Angamaly",
    "current_locality": "Thrippunithura",
    "age": 52,
    "weight": 56.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 9,
    "total_donations": 1,
    "ml_score": 0.79
  },
  {
    "id": 186,
    "name": "Geethu Rajan",
    "email": "geethurajan1466@gmail.com",
    "contact": "9631868938",
    "place_of_residence": "Nellikuzhi",
    "current_locality": "Kodungallur",
    "age": 26,
    "weight": 46.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 2,
    "ml_score": 0.79
  },
  {
    "id": 105,
    "name": "Arjun Panicker",
    "email": "arjunpanicker4166@gmail.com",
    "contact": "8785239663",
    "place_of_residence": "Kozhikode",
    "current_locality": "Edapally",
    "age": 36,
    "weight": 68.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 3,
    "total_donations": 0,
    "ml_score": 0.78
  },
  {
    "id": 146,
    "name": "Ribin Rajan",
    "email": "ribinrajan2150@outlook.com",
    "contact": "9735408573",
    "place_of_residence": "Alappuzha",
    "current_locality": "Chalakudy",
    "age": 45,
    "weight": 64.0,
    "blood_group": "A+",
    "availability": false,
    "months_since_last_donation": 3,
    "total_donations": 0,
    "ml_score": 0.78
  },
  {
    "id": 174,
    "name": "Rajesh Paul",
    "email": "rajeshpaul2419@outlook.com",
    "contact": "8827888858",
    "place_of_residence": "Thrissur",
    "current_locality": "Kakkanad",
    "age": 27,
    "weight": 83.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 8,
    "total_donations": 3,
    "ml_score": 0.78
  },
  {
    "id": 60,
    "name": "Zayed masood",
    "email": "zayedmazod@gmail.com",
    "contact": "7577530176",
    "place_of_residence": "Ernakulam",
    "current_locality": "Kothamangalam",
    "age": 35,
    "weight": 90.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 4,
    "total_donations": 2,
    "ml_score": 0.77
  },
  {
    "id": 94,
    "name": "Nithin Menon",
    "email": "nithinmenon704@yahoo.com",
    "contact": "8577022327",
    "place_of_residence": "Kalamassery",
    "current_locality": "Kannur",
    "age": 26,
    "weight": 52.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 10,
    "total_donations": 3,
    "ml_score": 0.77
  },
  {
    "id": 96,
    "name": "Thomas Das",
    "email": "thomasdas6682@yahoo.com",
    "contact": "8652147315",
    "place_of_residence": "Kozhikode",
    "current_locality": "Piravom",
    "age": 30,
    "weight": 61.0,
    "blood_group": "AB+",
    "availability": false,
    "months_since_last_donation": 7,
    "total_donations": 0,
    "ml_score": 0.76
  },
  {
    "id": 97,
    "name": "Uma Mohammed",
    "email": "umamohammed7762@outlook.com",
    "contact": "7038578932",
    "place_of_residence": "Ernakulam",
    "current_locality": "Thrippunithura",
    "age": 50,
    "weight": 63.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 7,
    "total_donations": 0,
    "ml_score": 0.76
  },
  {
    "id": 129,
    "name": "Rekha Thomas",
    "email": "rekhathomas9023@gmail.com",
    "contact": "8257823277",
    "place_of_residence": "Thripunithura",
    "current_locality": "Kochi",
    "age": 30,
    "weight": 80.0,
    "blood_group": "AB+",
    "availability": false,
    "months_since_last_donation": 6,
    "total_donations": 0,
    "ml_score": 0.76
  },
  {
    "id": 80,
    "name": "Amal Nair",
    "email": "amalnair6094@hotmail.com",
    "contact": "8883674750",
    "place_of_residence": "Pothanicad",
    "current_locality": "Kothamangalam",
    "age": 47,
    "weight": 49.0,
    "blood_group": "A+",
    "availability": false,
    "months_since_last_donation": 6,
    "total_donations": 2,
    "ml_score": 0.75
  },
  {
    "id": 115,
    "name": "Serena George",
    "email": "serenageorge5692@yahoo.com",
    "contact": "9728721105",
    "place_of_residence": "Kozhikode",
    "current_locality": "Perumbavoor",
    "age": 48,
    "weight": 84.0,
    "blood_group": "A-",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 1,
    "ml_score": 0.75
  },
  {
    "id": 137,
    "name": "Unnikrishnan Varma",
    "email": "unnikrishnanvarma6079@outlook.com",
    "contact": "8175592652",
    "place_of_residence": "Kodungallur",
    "current_locality": "Pathanamthitta",
    "age": 53,
    "weight": 53.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 7,
    "total_donations": 2,
    "ml_score": 0.75
  },
  {
    "id": 140,
    "name": "Blesson Shibu",
    "email": "blessonshibu8833@hotmail.com",
    "contact": "9659118263",
    "place_of_residence": "Kollam",
    "current_locality": "Alappuzha",
    "age": 39,
    "weight": 65.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 9,
    "total_donations": 0,
    "ml_score": 0.75
  },
  {
    "id": 187,
    "name": "Dileep Khan",
    "email": "dileepkhan8958@outlook.com",
    "contact": "9090280311",
    "place_of_residence": "Kakkanad",
    "current_locality": "Kasaragod",
    "age": 21,
    "weight": 83.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 1,
    "ml_score": 0.75
  },
  {
    "id": 87,
    "name": "Minu Kurup",
    "email": "minukurup5713@yahoo.com",
    "contact": "9110302349",
    "place_of_residence": "Alappuzha",
    "current_locality": "Irinjalakuda",
    "age": 43,
    "weight": 65.0,
    "blood_group": "A+",
    "availability": false,
    "months_since_last_donation": 11,
    "total_donations": 0,
    "ml_score": 0.73
  },
  {
    "id": 110,
    "name": "Anu Pillai",
    "email": "anupillai2241@yahoo.com",
    "contact": "9086711862",
    "place_of_residence": "Pothanicad",
    "current_locality": "Kollam",
    "age": 36,
    "weight": 64.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 12,
    "total_donations": 0,
    "ml_score": 0.73
  },
  {
    "id": 91,
    "name": "Salu Babu",
    "email": "salubabu2480@outlook.com",
    "contact": "9023489766",
    "place_of_residence": "Kozhikode",
    "current_locality": "Kunnamkulam",
    "age": 36,
    "weight": 50.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 12,
    "total_donations": 2,
    "ml_score": 0.72
  },
  {
    "id": 1,
    "name": "Fasalul Fidha P P",
    "email": "fasalulfidha1011@gmail.com",
    "contact": "9061708347",
    "place_of_residence": "Malappuram",
    "current_locality": "Muvattupuzha",
    "age": 22,
    "weight": 49.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 2,
    "name": "Shahna Sherin T",
    "email": "shahnasherin2077@gmail.com",
    "contact": "7907599118",
    "place_of_residence": "Malappuram",
    "current_locality": "Muvattupuzha",
    "age": 21,
    "weight": 48.0,
    "blood_group": "B+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 3,
    "name": "Anagha A S",
    "email": "anaghaajith1224@gmail.com",
    "contact": "7736208938",
    "place_of_residence": "Trivandrum",
    "current_locality": "Kothamangalam",
    "age": 20,
    "weight": 45.0,
    "blood_group": "A+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 5,
    "name": "Nadeer K N",
    "email": "nazeernadeer36@gmail.com",
    "contact": "8137081787",
    "place_of_residence": "Ernakulam",
    "current_locality": "Aluva",
    "age": 20,
    "weight": 95.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 9,
    "name": "Abil Ameen",
    "email": "ameenabil07@gmail.com",
    "contact": "8590377953",
    "place_of_residence": "Ernakulam",
    "current_locality": "Irumalapadi",
    "age": 20,
    "weight": 52.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 11,
    "name": "Alshif T A",
    "email": "crazyinfo2424@gmail.com",
    "contact": "8281531243",
    "place_of_residence": "Ernakulam",
    "current_locality": "Thodupuzha",
    "age": 20,
    "weight": 45.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 22,
    "name": "Jagannath K A",
    "email": "jaggu2047@gmail.com",
    "contact": "9846677442",
    "place_of_residence": "Ernakulam",
    "current_locality": "Aluva",
    "age": 21,
    "weight": 35.0,
    "blood_group": "A+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 26,
    "name": "Fathima Noor T P",
    "email": "nooranichu9@gmail.com",
    "contact": "9188087363",
    "place_of_residence": "Malappuram",
    "current_locality": "Muvattupuzha",
    "age": 20,
    "weight": 48.0,
    "blood_group": "B-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 28,
    "name": "Fathima M J",
    "email": "fma793035@gmail.com",
    "contact": "8891700163",
    "place_of_residence": "Ernakulam",
    "current_locality": "Nellikuzhi",
    "age": 21,
    "weight": 53.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 29,
    "name": "Hadiya K S",
    "email": "Hadiyashafeek@gmail.com",
    "contact": "9037378175",
    "place_of_residence": "Ernakulam",
    "current_locality": "Aluva",
    "age": 21,
    "weight": 52.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 30,
    "name": "Amila M B",
    "email": "amilamb2005@gmail.com",
    "contact": "9562057646",
    "place_of_residence": "Ernakulam",
    "current_locality": "Muvattupuzha",
    "age": 21,
    "weight": 37.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 33,
    "name": "Khadeeja",
    "email": "Khadeeja568@gmail.com",
    "contact": "6282150092",
    "place_of_residence": "Ernakulam",
    "current_locality": "Perumbavoor",
    "age": 21,
    "weight": 51.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 35,
    "name": "Suhana P S",
    "email": "Suhanapsulfi@gmail.com",
    "contact": "8714055483",
    "place_of_residence": "Ernakulam",
    "current_locality": "Perumattam",
    "age": 23,
    "weight": 52.0,
    "blood_group": "A+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 36,
    "name": "Akshaya V",
    "email": "Akshayavichu2005@gmail.com",
    "contact": "7025760142",
    "place_of_residence": "Ernakulam",
    "current_locality": "Kolenchery",
    "age": 20,
    "weight": 54.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 38,
    "name": "Alby Eldho",
    "email": "albyeldhoci@gmail.com",
    "contact": "7306491192",
    "place_of_residence": "Ernakulam",
    "current_locality": "Muvattupuzha",
    "age": 20,
    "weight": 47.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 42,
    "name": "Aleesa Ashraf",
    "email": "Aleesaashraf@gmail.com",
    "contact": "9562939134",
    "place_of_residence": "Ernakulam",
    "current_locality": "Kothamangalam",
    "age": 21,
    "weight": 54.0,
    "blood_group": "A-",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 43,
    "name": "Fathima Shahla",
    "email": "fathimashahla564@gmail.com",
    "contact": "8714709951",
    "place_of_residence": "Malappuram",
    "current_locality": "Thrissur",
    "age": 22,
    "weight": 44.0,
    "blood_group": "O+",
    "availability": false,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 44,
    "name": "Ayisha Fiba",
    "email": "fibamhd74@gmail.com",
    "contact": "8157916151",
    "place_of_residence": "Malappuram",
    "current_locality": "Muvattupuzha",
    "age": 21,
    "weight": 51.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 45,
    "name": "Santumol C",
    "email": "santuputhiyaparambil@gmail.com",
    "contact": "9061983944",
    "place_of_residence": "Kottayam",
    "current_locality": "Muvattupuzha",
    "age": 27,
    "weight": 50.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 56,
    "name": "Fathimath Hanna",
    "email": "hannashahid@gmail.com",
    "contact": "9526128712",
    "place_of_residence": "Malappuram",
    "current_locality": "Parappanaghadi",
    "age": 30,
    "weight": 54.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 63,
    "name": "Abhinand",
    "email": "aabhinandmysunil@gmail.com",
    "contact": "7025075657",
    "place_of_residence": "Muvattupuzha",
    "current_locality": "Muvattupuzha",
    "age": 19,
    "weight": 54.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 64,
    "name": "Dhanush shibu",
    "email": "dhanushshibu111@gmail.com",
    "contact": "9645470848",
    "place_of_residence": "Muvattupuzha",
    "current_locality": "Muvattupuzha",
    "age": 20,
    "weight": 85.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 67,
    "name": "Anu m s",
    "email": "anums@icet.ac.in ",
    "contact": "9562737283",
    "place_of_residence": "Nellikushi",
    "current_locality": "Nellikushi",
    "age": 35,
    "weight": 52.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 69,
    "name": "Abin Jas",
    "email": "jasjas321@gmail.com",
    "contact": "8137983070",
    "place_of_residence": "Malappuram",
    "current_locality": "Kothamangalam",
    "age": 24,
    "weight": 88.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 70,
    "name": "Nithul Santhosh",
    "email": "nithulsanthosh9747@gmail.com",
    "contact": "7510253011",
    "place_of_residence": "Pothanicad",
    "current_locality": "Ernakulam,Kerala",
    "age": 23,
    "weight": 50.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 82,
    "name": "Nithya Mohan",
    "email": "nithyamohan2432@hotmail.com",
    "contact": "8067276135",
    "place_of_residence": "Irinjalakuda",
    "current_locality": "Guruvayur",
    "age": 38,
    "weight": 54.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 101,
    "name": "Abhilash Paul",
    "email": "abhilashpaul7694@outlook.com",
    "contact": "8262483764",
    "place_of_residence": "Thrippunithura",
    "current_locality": "Kalampoor",
    "age": 55,
    "weight": 53.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 118,
    "name": "Sneha Thomas",
    "email": "snehathomas544@outlook.com",
    "contact": "9586651400",
    "place_of_residence": "Muvattupuzha",
    "current_locality": "Alappuzha",
    "age": 18,
    "weight": 89.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 145,
    "name": "Dinesh Philip",
    "email": "dineshphilip641@outlook.com",
    "contact": "9541078179",
    "place_of_residence": "Thrissur",
    "current_locality": "Malappuram",
    "age": 27,
    "weight": 95.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 0,
    "total_donations": 0,
    "ml_score": 0.71
  },
  {
    "id": 151,
    "name": "Anitha Mohammed",
    "email": "anithamohammed9901@outlook.com",
    "contact": "9693104459",
    "place_of_residence": "Guruvayur",
    "current_locality": "Kasaragod",
    "age": 53,
    "weight": 98.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 6,
    "total_donations": 1,
    "ml_score": 0.71
  },
  {
    "id": 103,
    "name": "Nidhin Menon",
    "email": "nidhinmenon5689@gmail.com",
    "contact": "8184215534",
    "place_of_residence": "Kottayam",
    "current_locality": "Perumbavoor",
    "age": 42,
    "weight": 86.0,
    "blood_group": "O+",
    "availability": true,
    "months_since_last_donation": 9,
    "total_donations": 1,
    "ml_score": 0.7
  },
  {
    "id": 92,
    "name": "Krishnan Das",
    "email": "krishnandas6915@yahoo.com",
    "contact": "7562869703",
    "place_of_residence": "Thrissur",
    "current_locality": "Pothanicad",
    "age": 52,
    "weight": 82.0,
    "blood_group": "O-",
    "availability": true,
    "months_since_last_donation": 3,
    "total_donations": 0,
    "ml_score": 0.69
  },
  {
    "id": 113,
    "name": "Nikhil Siddiqui",
    "email": "nikhilsiddiqui2372@gmail.com",
    "contact": "8699159162",
    "place_of_residence": "Aluva",
    "current_locality": "Kasaragod",
    "age": 39,
    "weight": 88.0,
    "blood_group": "AB+",
    "availability": true,
    "months_since_last_donation": 4,
    "total_donations": 0,
    "ml_score": 0.69
  },
  {
    "id": 95,
    "name": "Bindhu Mathew",
    "email": "bindhumathew6771@hotmail.com",
    "contact": "8506428558",
    "place_of_residence": "Kodungallur",
    "current_locality": "Moovattupuzha",
    "age": 19,
    "weight": 99.0,
    "blood_group": "B-",
    "availability": true,
    "months_since_last_donation": 6,
    "total_donations": 0,
    "ml_score": 0.67
  },
  {
    "id": 108,
    "name": "Mohammed George",
    "email": "mohammedgeorge7287@hotmail.com",
    "contact": "8095808582",
    "place_of_residence": "Kunnamkulam",
    "current_locality": "Kalampoor",
    "age": 55,
    "weight": 96.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 6,
    "total_donations": 0,
    "ml_score": 0.67
  },
  {
    "id": 124,
    "name": "Vrinda George",
    "email": "vrindageorge30@hotmail.com",
    "contact": "9403827950",
    "place_of_residence": "Moovattupuzha",
    "current_locality": "Kalampoor",
    "age": 19,
    "weight": 88.0,
    "blood_group": "A-",
    "availability": true,
    "months_since_last_donation": 6,
    "total_donations": 0,
    "ml_score": 0.67
  },
  {
    "id": 149,
    "name": "Sandhya Jose",
    "email": "sandhyajose9941@hotmail.com",
    "contact": "8558904787",
    "place_of_residence": "Pathanamthitta",
    "current_locality": "Kollam",
    "age": 43,
    "weight": 88.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 7,
    "total_donations": 0,
    "ml_score": 0.67
  },
  {
    "id": 111,
    "name": "Suresh Raj",
    "email": "sureshraj2581@outlook.com",
    "contact": "8241547613",
    "place_of_residence": "Thrippunithura",
    "current_locality": "Kunnamkulam",
    "age": 29,
    "weight": 92.0,
    "blood_group": "AB+",
    "availability": false,
    "months_since_last_donation": 8,
    "total_donations": 0,
    "ml_score": 0.66
  },
  {
    "id": 112,
    "name": "Lekha Pillai",
    "email": "lekhapillai7358@yahoo.com",
    "contact": "8891868565",
    "place_of_residence": "Kaloor",
    "current_locality": "Ernakulam",
    "age": 39,
    "weight": 86.0,
    "blood_group": "A+",
    "availability": true,
    "months_since_last_donation": 8,
    "total_donations": 0,
    "ml_score": 0.66
  },
  {
    "id": 119,
    "name": "Jomon Pillai",
    "email": "jomonpillai9954@outlook.com",
    "contact": "8182107311",
    "place_of_residence": "Thrissur",
    "current_locality": "Ernakulam",
    "age": 44,
    "weight": 99.0,
    "blood_group": "B+",
    "availability": true,
    "months_since_last_donation": 8,
    "total_donations": 0,
    "ml_score": 0.66
  },
  {
    "id": 175,
    "name": "Pradeep Biju",
    "email": "pradeepbiju7929@yahoo.com",
    "contact": "7059664849",
    "place_of_residence": "Kannur",
    "current_locality": "Kalampoor",
    "age": 53,
    "weight": 85.0,
    "blood_group": "AB-",
    "availability": true,
    "months_since_last_donation": 10,
    "total_donations": 0,
    "ml_score": 0.65
  }
];

export default donorsData;